Sync install-beyondcorp-runtime. (#28)
* Sync install-beyondcorp-runtime.

* Sync install-beyondcorp-runtime.

diff --git a/bash-scripts/install-beyondcorp-runtime b/bash-scripts/install-beyondcorp-runtime
--- a/bash-scripts/install-beyondcorp-runtime
+++ b/bash-scripts/install-beyondcorp-runtime
@@ -21,7 +21,7 @@ set -euo pipefail
 
 readonly BEYONDCORP_REPOSITORIES='gcr.io/appconnector-external-release'
 readonly REMOTE_AGENT_REPOSITORY="${BEYONDCORP_REPOSITORIES}/appconnector_remote_cp"
-readonly REMOTE_AGENT_TAG='appconnector_remote_cp_20220110_rc00'
+readonly REMOTE_AGENT_TAG='appconnector_remote_cp_20220314_rc00'
 readonly REMOTE_AGENT_INSTALLER_IMAGE="${REMOTE_AGENT_REPOSITORY}:${REMOTE_AGENT_TAG}"
 readonly REMOTE_AGENT_RUNNER_TARGET_IMAGE="${REMOTE_AGENT_REPOSITORY}:${REMOTE_AGENT_TAG}"
 readonly REMOTE_AGENT_RUNNER_STABLE_IMAGE="${REMOTE_AGENT_REPOSITORY}:${REMOTE_AGENT_TAG}"
@@ -32,6 +32,7 @@ readonly BEYONDCORP_SERVICE='beyondcorp'
 readonly BEYONDCORP_DIR='/var/beyondcorp'
 
 readonly COLOR_GREEN='\033[32m'
+readonly COLOR_RED='\033[31m'
 readonly COLOR_RESET='\033[0m'
 
 BEYONDCORP_USER='beyondcorp'
@@ -84,6 +85,13 @@ install_complete_message() {
 # sudo systemctl start beyondcorp & sudo systemctl enable beyondcorp | start  #
 # sudo systemctl status beyondcorp                                   | status #
 # --------------------------------------------------------------------------- #
+#                                                                             #
+# BeyondCorp utility scripts for verifying Remote Agent environment setup:    #
+# --------------------------------------------------------------------------- #
+# sudo /var/beyondcorp/scripts/run-diagnostics         | General diagnostics  #
+# sudo /var/beyondcorp/scripts/run-pre-install-checks  | Pre-install checks   #
+# sudo /var/beyondcorp/scripts/run-post-install-checks | Post-install checks  #
+# --------------------------------------------------------------------------- #
 ###############################################################################
 EOM
 )"
@@ -132,8 +140,24 @@ check_dependency() {
 
 precondition_checks() {
   title 'Checking dependencies...'
-  check_dependency "docker" "docker version" "Please install Docker Engine on this machine (https://docs.docker.com/engine/install/)."
+  check_dependency "docker" "docker --version" "Please install Docker Engine on this machine (https://docs.docker.com/engine/install/)."
+
+  # Enabling root privileges for the $USER
+  if [[ "${USER}" != 'root' ]] && ! (id -nG "${USER}" | grep -qw "docker") ; then
+    INFO "Appending user '${USER}' to group 'docker'."
+    if ! sudo usermod -aG "docker" "${USER}"; then
+      FATAL "Failed to append user '${USER}' to group 'docker'."
+    fi
+    printf "%b%s%b\n" "${COLOR_RED}" "Updated group membership for '${USER}'. Please log out and log back in for the changes to be re-evaluated and run the installation script again." "${COLOR_RESET}"
+    exit
+  fi
+
   check_dependency "systemctl" "systemctl --version" "Please install systemctl on this machine (https://www.man7.org/linux/man-pages/man1/systemctl.1.html)."
+}
+
+installation_checks() {
+  title 'Checking BeyondCorp Remote Agent environment...'
+  sudo "${BEYONDCORP_DIR}/scripts/run-pre-install-checks"
 }
 
 # 3. user
@@ -304,5 +328,6 @@ fi
 precondition_checks
 add_user
 install
+installation_checks
 start_service
 install_complete_message
